version: '3'
services:
  worker:
    build: ./DockerFiles/Worker
    ports:
      - ${LOCAL_IP}:${SERVER_PORT}:80
      - ${LOCAL_IP}:22:22
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ${LOCAL_DEV_DIR}:/var/www
  mysql:
    build: ./DockerFiles/Mysql
    ports:
      - ${LOCAL_IP}:3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
